name: Node Continuous Integration
on: push
jobs:
    build-project:
        name: Build project
        runs-on: ubuntu-latest
        container: node:16
        steps:
            - run: node --version
              name: Check Node version
            - run: npm --version
              name: Check NPM version
            - uses: actions/checkout@v4
              name: Checkout code from GitHub
            - run: npm install
              name: Install NPM packages
            - run: node app.js
              name: Run Node application
            - name: Upload static site content
              uses: actions/upload-artifact@v3
              with:
                name: static-site
                path: .next/
    release-project:
        name: Release project
        runs-on: ubuntu-latest
        container: node:16
        steps:
            - run: node app.js
              name: Run Node application
